const global_seriousSentences = [
  "I like to juggle my balls when I'm stressed.",
  "My balls dropped once...",
  "Don't touch my balls unless you're planning to play.",
  "I keep my balls in a velvet sack—only the best for them.",
  "Her dog wouldn't stop chasing my balls.",
  "My balls are bigger than they look on camera.",
  "These balls need a little polish before the big event.",
  "I lost my balls in the grass and cried for hours.",
  "You've got some balls showing up here uninvited!",
  "My balls clanked together—it was a cold day.",
  "I oil my balls regularly for peak performance.",
  "He got kicked in the balls—both emotionally and physically.",
  "I don't always play with balls, but when I do, it's intense.",
  "Those aren't stress balls—they're just my personality.",
  "My grandma knitted me a sack for my balls.",
  "My balls were bouncing all over the place—it was chaos.",
  "She complimented my balls—said they had a nice texture.",
  "He tripped and landed face-first in my balls.",
  "Those are some high-maintenance balls you've got there.",
  "I keep my balls in separate drawers—can't let them touch.",
  "My balls don't work in the rain—they get slippery.",
  "These balls have seen some serious action.",
  "I buff my balls with a microfiber cloth every morning.",
  "Never trust a man with dusty balls.",
  "My balls dropped during the Zoom call—it was awkward.",
  "She tried to juggle too many balls and lost.",
  "I spent the weekend organizing my balls by color.",
  "Please don't judge me—I collect balls for fun.",
  "My balls are limited edition—you won't find these in stores.",
  "Every time I drop my balls, someone steps on them.",
  "She complimented how round my balls were—made my day.",
  "I keep my balls in a display case—they're too pretty to use.",
  "Nothing beats a quiet evening shining my balls.",
  "My balls don't bounce like they used to—must be age.",
  "I lent him my balls once and never got them back.",
  "I was proud until someone said my balls looked deflated.",
  "I always carry spare balls—just in case.",
  "My cat won't stop batting my balls around the house.",
  "He tried to juggle three balls and hit the ceiling fan.",
  "She gasped and said, 'Wow, those are some smooth balls!'",
  "You can tell a lot about a person by how they handle balls."
];